echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-29 "
echo "We are learning AWS, Azure DevOps and DevSecOps"
echo "I am learning AWS"
echo "This is my first practical in AWS EC2"
